


#### std::nullptr_t
std::nullptr_t 是空指针字面量 nullptr 的类型。它是既非指针类型亦非指向成员指针类型的独立类型。


#### std::size_t
std::size_t 是 sizeof 运算符还有 sizeof... 运算符和 alignof 运算符 (C++11 起)所返回的无符号整数类型。
std::size_t 可以存放下理论上可能存在的对象的最大大小，该对象可以是任何类型，包括数组。
std::size_t 可以存放下任何非成员的指针，此时可以视作其与 std::uintptr_t 同义。
在对诸如 std::string、std::vector 等 C++ 容器进行索引操作时，正确的类型是该容器的成员 typedef size_type，而该类型通常被定义为与 std::size_t 相同。

#### std::raise
发送信号 sig 给程序。调用信号处理函数（用 std::signal() 函数指定）。
若仍未用 std::signal() 设置用户定义的处理策略，则忽略信号还是调用默认处理函数是实现定义的。
sig	-	要发送的信号。可以是实现定义值或下列值之一：
|常量|	解释|
|:--:|:--|
|SIGTERM	|发送给程序的终止请求|
|SIGSEGV	|非法内存访问(分段错误)|
|SIGINT     |外部中断，通常为用户所起始|
|SIGILL	    |非法程序映像，例如非法指令|
|SIGABRT	|异常终止条件，例如为 std::abort() 所起始|
|SIGFPE	    |错误算术运算，例如除以零|

```cpp
#include <csignal>
#include <iostream>
 
void signal_handler(int signal)
{
    std::cout << "Received signal " << signal << '\n';
}
 
int main()
{
    // 安装信号处理函数
    std::signal(SIGTERM, signal_handler);
 
    std::cout << "Sending signal " << SIGTERM << '\n';
    std::raise(SIGTERM);
}


```


#### std::abort
导致不正常程序终止，除非传递给 std::signal 的信号处理函数正在捕捉 SIGABRT ，且该处理函数不返回。
不调用拥有自动、线程局域 (C++11 起)和静态存储期的对象的析构函数。
亦不调用以 std::atexit() 和 std::at_quick_exit (C++11 起) 注册的函数。
```cpp
int main()
{
    Tester automatic_tester; // 不调用析构函数
 
    // 安装处理函数
    auto previous_handler = std::signal(SIGABRT, signal_handler);
    if (previous_handler == SIG_ERR) {
        std::cerr << "Setup failed\n";
        return EXIT_FAILURE;
    }
 
    std::abort();  // 引发 SIGABRT
    std::cout << "This code is unreachable\n";
}
```


#### std::_Exit
[[noreturn]] void _Exit( int exit_code ) noexcept;
导致正常程序终止出现，而不清理资源。
不调用拥有自动、线程局域和静态存储期对象的析构函数。不调用传递给 std::at_quick_exit() 或 std::atexit() 的函数。
若 exit_code 为 0 或 EXIT_SUCCESS ，则返回宿主环境指示成功终止的实现定义状态。若 exit_code 为 EXIT_FAILURE ，则返回指示不成功终止的实现定义状态。

##### std::atexit
1. int atexit( /*c-atexit-handler*/* func );
2. int atexit( /*atexit-handler*/* func );
3. int atexit( /*c-atexit-handler*/* func ) noexcept;
4. int atexit( /*atexit-handler*/* func ) noexcept;
注册 func 所指向的函数，使得在正常程序中止（通过 std::exit() 或从 main 函数返回）时调用它。




##### std::exit
1. void exit( int exit_code );
2. [[noreturn]] void exit( int exit_code );



